modifications to get local build/test scenario working
TravisEz13/PSPackageProject pull request #14
Opened 2019-07-25 17:48 UTC by JamesWTruher

Here's the scenario that works end to end

```powershell
PS> import-module -force ./PSPackageProject.psd1
PS> Initialize-PSPackageProject -modulename mymod -ModuleBase /tmp/mb                                 
PS> cd /tmp/mb      
/tmp/mb
PS> ./build -build
VERBOSE: Invoking build script
VERBOSE: Starting DoBuild
VERBOSE: Copying module files to '/tmp/mb/out/mymod'
VERBOSE: Copying help files to '/tmp/mb/out/mymod'
VERBOSE: Building assembly and copying to '/tmp/mb/out/mymod'
VERBOSE: Ending DoBuild
VERBOSE: Finished invoking build script
PS> ./build -test
WARNING: The names of some imported commands from the module 'mymod' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
Executing all tests in 'Test'

Executing script /private/tmp/mb/Test/mymod.Tests.ps1

  Describing Test mymod
    [+] This is the first test for mymod 82ms
Tests completed in 347ms
Tests Passed: 1, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0 
```

Questionable code is the call to the test code, still missing is the help building code

2019-07-25 18:26 UTC, adityapatwardhan requested changes

2019-07-25 18:26 UTC, adityapatwardhan commented on src/PSPackageProject.psm1
> +        SourcePath = Join-Path $moduleRoot "src"
We do not want to set full paths here. They will not make any sense in CI. My PR #13 sets them dynamically when `Get-PSPackageProjectConfig` is called.

2019-07-25 18:26 UTC, adityapatwardhan commented on src/build_for_init.ps1
> +    copy-item -Recurse "${SrcPath}/Help/${Culture}" "${OutDirectory}/${ModuleName}"
**H**elp -> **h**elp

2019-07-25 18:26 UTC, adityapatwardhan commented on src/build_for_init.ps1
> +    copy-item -Recurse "${SrcPath}/Help/${Culture}" "${OutDirectory}/${ModuleName}"
planning to standardize on all small case.

2019-07-25 18:26 UTC, adityapatwardhan commented on src/build_for_init.ps1
> +if ( ! ( Get-Module -EA SilentlyContinue PSPackageProject) ) {
EA -> ErrorAction

2019-07-25 18:26 UTC, adityapatwardhan commented on src/build_for_init.ps1
> +    $ps = (Get-Process -id $PID).MainModule.FileName
We should just call `Invoke-PSPackageProjectTest -Type Functional` and `Invoke-PSPackageProjectTest -Type StaticAnalysis` here.

2019-07-25 22:55 UTC, adityapatwardhan requested changes

2019-07-25 22:55 UTC, adityapatwardhan commented on src/PSPackageProject.psm1
> +            $resultFile = Invoke-FunctionalValidation -testPath test
test -> $config.TestPath

2019-07-26 00:26 UTC, TravisEz13 commented on src/PSPackageProject.psm1
> +            $resultFile = Invoke-FunctionalValidation -testPath test
```suggestion
            $resultFile = Invoke-FunctionalValidation -testPath $config.TestPath
```

2019-07-26 00:28 UTC, merged